#ifndef QTWIDGETS_INCLUDE_NAMESPACE_H_
#define QTWIDGETS_INCLUDE_NAMESPACE_H_

#include "config.h"

#if DISABLE_FNRICE_QT_WIDGET_NAMESPACE

# define FNRICE_QT_WIDGETS_PREPEND_NAMESPACE(name) ::name
# define FNRICE_QT_WIDGETS_USE_NAMESPACE
# define FNRICE_QT_WIDGETS_BEGIN_NAMESPACE
# define FNRICE_QT_WIDGETS_END_NAMESPACE
# define FNRICE_QT_WIDGETS_BEGIN_INCLUDE_NAMESPACE
# define FNRICE_QT_WIDGETS_END_INCLUDE_NAMESPACE
# define FNRICE_QT_WIDGETS_FORWARD_DECLARE_CLASS(name) class name;
# define FNRICE_QT_WIDGETS_FORWARD_DECLARE_STRUCT(name) struct name;

#else /* user namespace */

#if FNRICE_QT_WIDGET_USING_CUSTOM_NAMESPACE /* custom namespace */
#define FNRICE_QT_WIDGET_NAMESPACE FNRICE_QT_WIDGET_CUSTOM_NAMESPACE
#else
#define FNRICE_QT_WIDGET_NAMESPACE fnRice::QtWidgets
#endif

# define FNRICE_QT_WIDGETS_PREPEND_NAMESPACE(name) ::FNRICE_QT_WIDGET_NAMESPACE::name
# define FNRICE_QT_WIDGETS_USE_NAMESPACE using namespace ::FNRICE_QT_WIDGET_NAMESPACE;
# define FNRICE_QT_WIDGETS_BEGIN_NAMESPACE namespace FNRICE_QT_WIDGET_NAMESPACE {
# define FNRICE_QT_WIDGETS_END_NAMESPACE }
# define FNRICE_QT_WIDGETS_BEGIN_INCLUDE_NAMESPACE }
# define FNRICE_QT_WIDGETS_END_INCLUDE_NAMESPACE namespace QT_NAMESPACE {
# define FNRICE_QT_WIDGETS_FORWARD_DECLARE_CLASS(name) \
    FNRICE_QT_WIDGETS_BEGIN_NAMESPACE class name; FNRICE_QT_WIDGETS_END_NAMESPACE \
    using FNRICE_QT_WIDGETS_PREPEND_NAMESPACE(name);
# define FNRICE_QT_WIDGETS_FORWARD_DECLARE_STRUCT(name) \
    FNRICE_QT_WIDGETS_BEGIN_NAMESPACE struct name; FNRICE_QT_WIDGETS_END_NAMESPACE \
    using FNRICE_QT_WIDGETS_PREPEND_NAMESPACE(name);

namespace FNRICE_QT_WIDGET_NAMESPACE {};

# endif /* user namespace */

#endif //QTWIDGETS_INCLUDE_NAMESPACE_H_
